use crate::errors::AppError;

pub async fn create_expense() -> Result<(), AppError> {
    Ok(())
}

pub async fn list_expenses() -> Result<(), AppError> {
    Ok(())
}

pub async fn update_expense(_id: i32) -> Result<(), AppError> {
    Ok(())
}

pub async fn delete_expense(_id: i32) -> Result<(), AppError> {
    Ok(())
}
