use crate::errors::AppError;

pub async fn create_order() -> Result<(), AppError> {
    Ok(())
}

pub async fn list_orders() -> Result<(), AppError> {
    Ok(())
}

pub async fn update_order(_id: i32) -> Result<(), AppError> {
    Ok(())
}

pub async fn delete_order(_id: i32) -> Result<(), AppError> {
    Ok(())
}
